---

- name: install and configure mysql server
  hosts: magento
  become: true
  vars_files:
    - vars/db.yml
  roles:
    - role: geerlingguy.mysql

- name: install php on webserver isntance
  hosts: magento
  become: true
  vars_files:
    - vars/php.yml
  roles:
    - role: geerlingguy.php 

- name: install java and opensearch
  hosts: magento
  become: true
  roles:
    - geerlingguy.java
    - opensearch

- name: install magento and konfigure vhost konfig
  hosts: magento
  become: true
  roles:
    - geerlingguy.nginx
    - magento



