- name: install and configure mysql server
  hosts: magento
  become: true
  roles:
    - role: mysql_8_0
    - role: php_8_3
    - role: nginx_1_24
    - role: java_17
    - role: opensearch_2_14
    - role: magento2_4_8_p4


