---
nginx_package_name: "nginx"
nginx_default_vhost_path: 
nginx_vhost_template: "vhost.j2"
nginx_vhost_path: /etc/nginx/sites-enabled
domain_name: "ec2-35-180-138-78.eu-west-3.compute.amazonaws.com"
nginx_service_state: started
nginx_service_enabled: true
nginx_default_vhost_path: /etc/nginx/sites-enabled/default