dependency: 
  name: galaxy
driver:  
  name: docker
platforms:
  - name: testinstance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    command: sleep infinity
    privileged: true
    tty: true
    docker_networks: []
    container_name: geerling
provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: /home/datascientest/Ansible_examen/roles
verifier: 
  name: testinfra 
